# Generated by Django 5.2 on 2025-04-21 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="工程名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "standard_time",
                    models.IntegerField(default=0, verbose_name="標準時間(分)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
            ],
            options={
                "verbose_name": "工程",
                "verbose_name_plural": "工程",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="製品名")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="製品コード"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "製品",
                "verbose_name_plural": "製品",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                ("location", models.CharField(max_length=100, verbose_name="保管場所")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                        verbose_name="製品",
                    ),
                ),
            ],
            options={
                "verbose_name": "在庫",
                "verbose_name_plural": "在庫",
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                ("planned_date", models.DateField(verbose_name="計画日")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "計画済"),
                            ("in_progress", "製造中"),
                            ("completed", "完了"),
                            ("canceled", "中止"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.process",
                        verbose_name="工程",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                        verbose_name="製品",
                    ),
                ),
            ],
            options={
                "verbose_name": "製造指示",
                "verbose_name_plural": "製造指示",
            },
        ),
    ]
