version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=product_management.settings
      - DATABASE_NAME=${RDS_DB_NAME}
      - DATABASE_USER=${RDS_USERNAME}
      - DATABASE_PASSWORD=${RDS_PASSWORD}
      - DATABASE_HOST=${RDS_HOSTNAME}
      - DATABASE_PORT=${RDS_PORT:-5432}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-'your-secret-key-here'}
      - DEBUG=False
      - ALLOWED_HOSTS=*
    volumes:
      - ./static:/app/static
      - ./media:/app/media
